/* CREATING DATABASE ANS TABLES */


CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM("M", "F") NOT NULL,
	CPF CHAR(11),
    FKEY_CARRO INT
);

CREATE TABLE TELEFONE(
	ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO VARCHAR(20) NOT NULL,
	TIPO ENUM("RES", "COM", "CEL"),
    FKEY_CLIENTE INT
);

CREATE TABLE MARCA(
	ID_MARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(20) NOT NULL
);

CREATE TABLE CARRO(
	ID_CARRO INT PRIMARY KEY AUTO_INCREMENT,
	ANO CHAR(4) NOT NULL,
    MODELO VARCHAR(20) NOT NULL,
    FKEY_MARCA INT
);

CREATE TABLE COR(
	ID_COR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(10)
);

CREATE TABLE CARRO_COR(

    FKEY_CARRO INT,
    FKEY_COR INT,
    PRIMARY KEY(FKEY_CARRO, FKEY_COR)

);




/* CONSTRAINTS */

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(FKEY_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(FKEY_CARRO) REFERENCES CARRO(ID_CARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(FKEY_MARCA) REFERENCES MARCA(ID_MARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(FKEY_COR) REFERENCES COR(ID_COR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_ID_CARRO
FOREIGN KEY(FKEY_CARRO) REFERENCES CARRO(ID_CARRO);

SHOW CREATE TABLE CLIENTE;
SHOW CREATE TABLE TELEFONE;
SHOW CREATE TABLE CARRO;
SHOW CREATE TABLE COR;
SHOW CREATE TABLE CARRO_COR;

/* BACKUP  */

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BACKUP_CLIENTE(

	IDBKP_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM("M", "F") NOT NULL,
	CPF CHAR(11),
	FKEY_CARRO INT

);

CREATE TABLE BACKUP_TELEFONE(

	IDBKP_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ID_TELEFONE INT,
	NUMERO VARCHAR(20) NOT NULL,
	TIPO ENUM('RES', 'COM', 'CEL'),
    FKEY_CLIENTE INT

);


/* TRIGGERS - DELETE & UPDATE */

USE PROJETO;

STATUS

DELIMITER $

CREATE TRIGGER BACKUP_CLIENTE_DEL
BEFORE DELETE ON CLIENTE
FOR EACH ROW
BEGIN
	
	INSERT INTO BACKUP.BACKUP_CLIENTE VALUES(NULL,OLD.ID_CLIENTE,
	OLD.NOME, OLD.SEXO, OLD.CPF, OLD.FKEY_CARRO, 'DELETE ACTION');

END
$

CREATE TRIGGER BACKUP_TELEFONE_DEL
BEFORE DELETE ON TELEFONE
FOR EACH ROW
BEGIN
	
	INSERT INTO BACKUP.BACKUP_TELEFONE VALUES(NULL, OLD.ID_TELEFONE,
	OLD.NUMERO, OLD.TIPO, OLD.FKEY_CLIENTE, 'DELETE ACTION');

END
$

CREATE TRIGGER BACKUP_TELEFONE_UPDATE
AFTER UPDATE ON TELEFONE
FOR EACH ROW
BEGIN
	
	INSERT INTO BACKUP.BACKUP_TELEFONE VALUES(NULL,OLD.ID_TELEFONE,
	OLD.NUMERO, NEW.NUMERO, OLD.TIPO, NEW.TIPO, OLD.FKEY_CLIENTE, 'UPDATE ACTION');

END
$

DELIMITER ;

SHOW TRIGGERS;


/* PROJECTIONS */

-- CAR PROJECTION

SELECT
CAR.MODELO,
CAR.ANO,
M.MARCA,
COR COR
FROM CARRO CAR
INNER JOIN MARCA M ON M.ID_MARCA = CAR.FKEY_MARCA
INNER JOIN CARRO_COR CC ON CC.FKEY_CARRO = CAR.ID_CARRO
INNER JOIN COR COR ON COR.ID_COR = CC.FKEY_COR;

-- ALL DATA PROJECTION

SELECT C.NOME,
		C.SEXO,
		C.CPF,
		T.NUMERO,
		T.TIPO,
		M.MARCA,
		CAR.MODELO,
		CAR.ANO, 
		COR.COR 
FROM CLIENTE C
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FKEY_CLIENTE
INNER JOIN CARRO CAR ON CAR.ID_CARRO = C.FKEY_CARRO
INNER JOIN MARCA M ON M.ID_MARCA = CAR.FKEY_MARCA
INNER JOIN CARRO_COR CC ON CC.FKEY_CARRO = CAR.ID_CARRO
INNER JOIN COR COR ON COR.ID_COR = CC.FKEY_COR;

SELECT COUNT(*), MARCA FROM MARCA
GROUP BY MARCA
ORDER BY 1;

SELECT COUNT(*), COR FROM COR
GROUP BY COR
ORDER BY 1;

SELECT NOME, COUNT(*), MODELO FROM CLIENTE C
INNER JOIN CARRO CAR
ON CAR.ID_CARRO = C.FKEY_CARRO;



/* PROCEDURE */

DELIMITER $

STATUS

-- CAD CLIENTE

CREATE PROCEDURE CAD_CLIENTE(C_NOME VARCHAR(30),
							C_SEXO ENUM("M", "F"),
							C_CPF CHAR(11),
							C_FKEY_CARRO INT)
BEGIN
	
	INSERT INTO CURSOS VALUES(NULL, C_NOME, C_SEXO, C_CPF, C_FKEY_CARRO);

END
$

-- CAD CARRO

CREATE PROCEDURE CAD_CARRO(C_ANO CHAR(4),
							C_MODELO VARCHAR(20),
							C_FKEY_MARCA INT)
BEGIN
	
	INSERT INTO CARRO VALUES(NULL, C_ANO, C_MODELO, C_FKEY_MARCA);

END
$

DELIMITER ;

CALL CAD_CLIENTE();
CALL CAD_CARRO();


/* VIEW */

CREATE VIEW CAR_VIEW AS 
SELECT
CAR.MODELO,
CAR.ANO,
M.MARCA,
COR COR
FROM CARRO CAR
INNER JOIN MARCA M ON M.ID_MARCA = CAR.FKEY_MARCA
INNER JOIN CARRO_COR CC ON CC.FKEY_CARRO = CAR.ID_CARRO
INNER JOIN COR COR ON COR.ID_COR = CC.FKEY_COR;

CREATE VIEW ALLDATA_VIEW AS 
SELECT C.NOME,
		C.SEXO,
		C.CPF,
		T.NUMERO,
		T.TIPO,
		M.MARCA,
		CAR.MODELO,
		CAR.ANO, 
		COR.COR 
FROM CLIENTE C
INNER JOIN TELEFONE T ON C.ID_CLIENTE = T.FKEY_CLIENTE
INNER JOIN CARRO CAR ON CAR.ID_CARRO = C.FKEY_CARRO
INNER JOIN MARCA M ON M.ID_MARCA = CAR.FKEY_MARCA
INNER JOIN CARRO_COR CC ON CC.FKEY_CARRO = CAR.ID_CARRO
INNER JOIN COR COR ON COR.ID_COR = CC.FKEY_COR;
